# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
