# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_products', '0003_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sizes',
            field=models.ManyToManyField(related_name='products', to='manage_products.Sizes'),
        ),
    ]
