# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_products', '0004_products_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='sizes',
        ),
        migrations.AddField(
            model_name='product_sizes',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='manage_products.Products'),
        ),
        migrations.AddField(
            model_name='product_sizes',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='manage_products.Sizes'),
        ),
    ]
