# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-01 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_products', '0007_auto_20170721_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(max_length=255, upload_to=b''),
        ),
    ]
