# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-01 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_products', '0008_auto_20170731_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
